spring:
  application:
    name: email-spot

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${EMAIL_SPOT_DB_URL}&password=${EMAIL_SPOT_DB_PASSWORD}&user=${EMAIL_SPOT_DB_USERNAME}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

